In [1]:

import pandas as pd
import numpy as np

#Read the training & testing data
training_data = pd.read_excel(r'Titanic_Survival_Train.xls',index_col=0,header=0)
testing_data=pd.read_excel(r'Titanic_Survival_Test.xls',index_col=0,header=0)
print(training_data.shape)
print(testing_data.shape)

(891, 11)
(21, 11)


In [2]:
training_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [3]:
testing_data.head()

Survived  Pclass  \
PassengerId                     
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   

                                                         Name     Sex   Age  \
PassengerId                                                                   
871                                         Balkic, Mr. Cerin    male  26.0   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0   
873                                  Carlsson, Mr. Frans Olof    male  33.0   
874                               Vander Cruyssen, Mr. Victor    male  47.0   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0   

             SibSp  Parch     Ticket     Fare        Cabin Embarked  
PassengerId                                                          
871              0      0     349248   7.8958          NaN        S  
872              1      1      11751  52.5542          D35        S  
873              0      0        695   5.0000  B51 B53 B55        S  
874              0      0     345765   9.0000          NaN        S  
875              1      0  P/PP 3381  24.0000          NaN        C

In [4]:
#feature selection
training_data = training_data[['Name','Pclass','Sex','Age','Survived']]
testing_data = testing_data[['Name','Pclass','Sex','Age','Survived']]
print(training_data.shape)
print(testing_data.shape)


(891, 5)
(21, 5)


In [5]:
training_data.describe(include='all')

Name      Pclass   Sex         Age    Survived
count                       891  891.000000   891  714.000000  891.000000
unique                      891         NaN     2         NaN         NaN
top     Braund, Mr. Owen Harris         NaN  male         NaN         NaN
freq                          1         NaN   577         NaN         NaN
mean                        NaN    2.308642   NaN   29.699118    0.383838
std                         NaN    0.836071   NaN   14.526497    0.486592
min                         NaN    1.000000   NaN    0.420000    0.000000
25%                         NaN    2.000000   NaN   20.125000    0.000000
50%                         NaN    3.000000   NaN   28.000000    0.000000
75%                         NaN    3.000000   NaN   38.000000    1.000000
max                         NaN    3.000000   NaN   80.000000    1.000000

In [6]:
#finding missing values
print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Name          0
Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         2
Survived    0
dtype: int64


In [7]:
#imputing numerical missing data with mean value

training_data["Age"].fillna(int(training_data["Age"].mean()),inplace=True)
print(training_data.isnull().sum())


#imputing numerical missing dara with mean value
testing_data["Age"].fillna(int(testing_data["Age"].mean()),inplace=True)
print(testing_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [8]:
#transforming categorical values to numerical values
from sklearn import preprocessing

colname=['Sex']

le=preprocessing.LabelEncoder()

for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    testing_data[x]=le.fit_transform(testing_data[x])
    

#training_data["Sex"]=training_data["Sex"].map({"female":0,"male":1})
#testing_data["Sex"]=testing_data["Sex"].map({"female":0,"male":1})

In [9]:
print(training_data.head())

                                                          Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0  


In [10]:
print(testing_data.head())

                                                         Name  Pclass  Sex  \
PassengerId                                                                  
871                                         Balkic, Mr. Cerin       3    1   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1    0   
873                                  Carlsson, Mr. Frans Olof       1    1   
874                               Vander Cruyssen, Mr. Victor       3    1   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)       2    0   

              Age  Survived  
PassengerId                  
871          26.0         0  
872          47.0         1  
873          33.0         0  
874          47.0         0  
875          28.0         1  


In [11]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      891 non-null    object 
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int32  
 3   Age       891 non-null    float64
 4   Survived  891 non-null    int64  
dtypes: float64(1), int32(1), int64(2), object(1)
memory usage: 38.3+ KB


In [12]:
X_train=training_data.values[0:870,1:-1]
Y_train=training_data.values[0:870,-1]
Y_train=Y_train.astype(int)

X_test=testing_data.values[:,1:-1]
Y_test=testing_data.values[:,-1]
Y_test=Y_test.astype(int)

In [13]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(870, 3)
(870,)
(21, 3)
(21,)


In [14]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X_train)
#scaler.fit_transform(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)



In [15]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='euclidean')

#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0)]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[14  0]
 [ 2  5]]
Classification report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93        14
           1       1.00      0.71      0.83         7

    accuracy                           0.90        21
   macro avg       0.94      0.86      0.88        21
weighted avg       0.92      0.90      0.90        21

Accuracy of the model:  0.9047619047619048


In [17]:
row = {'Pclass': 1 ,
           'Sex': 0,
           'Age': 16}
             
#Convert it into a dataframe
test_data = pd.DataFrame(data = row,index=[0])
test_data

Pclass  Sex  Age
0       1    0   16

In [18]:
test_data=scaler.transform(test_data)
test_data

array([[-1.56541549, -1.3610507 , -1.03776601]])

In [19]:
Y_pred_temp=model_KNN.predict(test_data)
Y_pred_temp

array([1])

In [20]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='manhattan')

#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0)]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[14  0]
 [ 2  5]]
Classification report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93        14
           1       1.00      0.71      0.83         7

    accuracy                           0.90        21
   macro avg       0.94      0.86      0.88        21
weighted avg       0.92      0.90      0.90        21

Accuracy of the model:  0.9047619047619048
