In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv("adult_new.csv")
df.head()

age         workclass  fnlwgt     education  educational-num  \
0   28         Local-gov  336951    Assoc-acdm               12   
1   44           Private  160323  Some-college               10   
2   63  Self-emp-not-inc  104626   Prof-school               15   
3   65           Private  184454       HS-grad                9   
4   48           Private  279724       HS-grad                9   

       marital-status         occupation relationship   race gender  \
0  Married-civ-spouse    Protective-serv      Husband  White   Male   
1  Married-civ-spouse  Machine-op-inspct      Husband  Black   Male   
2  Married-civ-spouse     Prof-specialty      Husband  White   Male   
3  Married-civ-spouse  Machine-op-inspct      Husband  White   Male   
4  Married-civ-spouse  Machine-op-inspct      Husband  White   Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0             0             0              40  United-States   >50K  
1          7688             0              40  United-States   >50K  
2          3103             0              32  United-States   >50K  
3          6418             0              40  United-States   >50K  
4          3103             0              48  United-States   >50K

In [3]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [9]:
for i in df.columns:
    print({i:df[i].unique()})

{'age': array([28, 44, 63, 65, 48, 43, 40, 34, 45, 46, 36, 22, 42, 41, 55, 33, 59,
       29, 27, 31, 58, 54, 37, 56, 39, 51, 50, 52, 47, 24, 64, 53, 35, 32,
       30, 68, 57, 66, 49, 38, 61, 73, 26, 23, 25, 62, 90, 60, 67, 69, 72,
       85, 71, 77, 70, 19, 21, 74, 75, 20, 81, 76, 80, 88, 78, 79, 84, 17,
       18, 82, 83, 86, 87], dtype=int64)}
{'workclass': array(['Local-gov', 'Private', 'Self-emp-not-inc', 'State-gov',
       'Self-emp-inc', '?', 'Federal-gov', 'Without-pay', 'Never-worked'],
      dtype=object)}
{'fnlwgt': array([336951, 160323, 104626, ...,  84661, 310152, 257302], dtype=int64)}
{'education': array(['Assoc-acdm', 'Some-college', 'Prof-school', 'HS-grad', 'Masters',
       'Doctorate', 'Bachelors', 'Assoc-voc', '9th', '10th', '7th-8th',
       '11th', '5th-6th', '1st-4th', '12th', 'Preschool'], dtype=object)}
{'educational-num': array([12, 10, 15,  9, 14, 16, 13, 11,  5,  6,  4,  7,  3,  2,  8,  1],
      dtype=int64)}
{'marital-status': array(['Married-civ-spous

In [10]:
df_new = df.replace('?',np.nan)

In [11]:
df_new.isnull().sum()

age                   0
workclass          1283
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         1288
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      508
income                0
dtype: int64

In [20]:
for i in ['workclass', 'occupation', 'native-country']:
    df_new[i].fillna(df_new[i].mode()[0], inplace=True)

In [21]:
df_new.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [25]:
catg_columns = []
for i in df_new.columns:
    if df[i].dtype == 'object':
        catg_columns.append(i)
catg_columns

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native-country',
 'income']

In [27]:
le = LabelEncoder()

for col in catg_columns:
    df_new[col] = le.fit_transform(df_new[col])

    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print("Feature: ", col)
    print("Mapping : ", le_name_mapping)

Feature:  workclass
Mapping :  {'Federal-gov': 0, 'Local-gov': 1, 'Never-worked': 2, 'Private': 3, 'Self-emp-inc': 4, 'Self-emp-not-inc': 5, 'State-gov': 6, 'Without-pay': 7}
Feature:  education
Mapping :  {'10th': 0, '11th': 1, '12th': 2, '1st-4th': 3, '5th-6th': 4, '7th-8th': 5, '9th': 6, 'Assoc-acdm': 7, 'Assoc-voc': 8, 'Bachelors': 9, 'Doctorate': 10, 'HS-grad': 11, 'Masters': 12, 'Preschool': 13, 'Prof-school': 14, 'Some-college': 15}
Feature:  marital-status
Mapping :  {'Divorced': 0, 'Married-AF-spouse': 1, 'Married-civ-spouse': 2, 'Married-spouse-absent': 3, 'Never-married': 4, 'Separated': 5, 'Widowed': 6}
Feature:  occupation
Mapping :  {'Adm-clerical': 0, 'Armed-Forces': 1, 'Craft-repair': 2, 'Exec-managerial': 3, 'Farming-fishing': 4, 'Handlers-cleaners': 5, 'Machine-op-inspct': 6, 'Other-service': 7, 'Priv-house-serv': 8, 'Prof-specialty': 9, 'Protective-serv': 10, 'Sales': 11, 'Tech-support': 12, 'Transport-moving': 13}
Feature:  relationship
Mapping :  {'Husband': 0, 'No

In [28]:
df_new.head()

age  workclass  fnlwgt  education  educational-num  marital-status  \
0   28          1  336951          7               12               2   
1   44          3  160323         15               10               2   
2   63          5  104626         14               15               2   
3   65          3  184454         11                9               2   
4   48          3  279724         11                9               2   

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0          10             0     4       1             0             0   
1           6             0     2       1          7688             0   
2           9             0     4       1          3103             0   
3           6             0     4       1          6418             0   
4           6             0     4       1          3103             0   

   hours-per-week  native-country  income  
0              40              38       1  
1              40              38       1  
2              32              38       1  
3              40              38       1  
4              48              38       1

In [34]:
X = df_new.values[:,0:-1]
Y = df_new.values[:,-1]
print(X.shape)
print(Y.shape)

(27414, 14)
(27414,)


In [36]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[-0.91080072, -1.82178236,  1.41055538, ..., -0.24549699,
        -0.13195044,  0.2536764 ],
       [ 0.30347105, -0.08150981, -0.27597356, ..., -0.24549699,
        -0.13195044,  0.2536764 ],
       [ 1.74541877,  1.65876274, -0.80779525, ..., -0.24549699,
        -0.78409618,  0.2536764 ],
       ...,
       [ 1.36595884, -0.08150981, -0.35630492, ..., -0.24549699,
        -0.13195044,  0.2536764 ],
       [-1.36615263, -0.08150981,  0.11710872, ..., -0.24549699,
        -1.76231478,  0.2536764 ],
       [ 0.91060693,  0.78862647,  0.94245069, ..., -0.24549699,
        -0.13195044,  0.2536764 ]])

In [38]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2, random_state=10)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(21931, 14)
(5483, 14)
(21931,)
(5483,)


In [40]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [42]:
y_pred = model.predict(x_test)
print(y_pred)
print(list(zip(y_pred,y_test)))

[1 1 1 ... 1 1 0]
[(1, 1), (1, 1), (1, 1), (0, 1), (1, 1), (1, 1), (1, 0), (0, 0), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 1), (0, 0), (1, 1), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0), (1, 1), (0, 1), (0, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 0), (1, 0), (0, 0), (0, 1), (1, 0), (0, 0), (1, 1), (1, 1), (0, 0), (1, 0), (1, 0), (0, 1), (1, 1), (0, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 0), (0, 0), (1, 1), (0, 1), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (0, 1), (0, 0), (0, 0), (1, 0), (0, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0

In [44]:
cfm = confusion_matrix(y_test,y_pred)
print(cfm)

print("classification report")
print(classification_report(y_test,y_pred))

acc = accuracy_score(y_test,y_pred)
print("Accuracy Score : ", acc)

[[2621  503]
 [ 738 1621]]
classification report
              precision    recall  f1-score   support

           0       0.78      0.84      0.81      3124
           1       0.76      0.69      0.72      2359

    accuracy                           0.77      5483
   macro avg       0.77      0.76      0.77      5483
weighted avg       0.77      0.77      0.77      5483

Accuracy Score :  0.7736640525259895


In [46]:
df_new['income'].value_counts()

0    15727
1    11687
Name: income, dtype: int64